CREATE DATABASE IF NOT EXISTS site_contato CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE site_contato;
CREATE TABLE IF NOT EXISTS mensagens (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  mensagem TEXT NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
